server:
  port: 9001

spring:
  application:
    name: service-aliyunvod
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB


aliyunvod:
  client:
    #endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI5tGfvrVpi5PGPkSBz7r6
    accessKeySecret: uctVKNUBh2G3lUeT6YQPcoOqmFDcYR
    #bucketName: guli-bucket-1024

